namespace DevOpsMigrationPlatform.Abstractions;

/// <summary>
/// The internal serialisable unit of execution handed from the CLI → Control Plane → Migration Agent.
/// The config file is never passed directly to the agent; only the MigrationJob is.
/// Schema: see .agents/context/job-contract.md
/// </summary>
public class MigrationJob
{
    /// <summary>Globally unique identifier (UUID v4). Generated by the CLI after pre-validation.</summary>
    public string JobId { get; init; } = string.Empty;

    /// <summary>Config schema version from the source config file.</summary>
    public string ConfigVersion { get; init; } = "1.0";

    /// <summary>Export, Import, or Both.</summary>
    public string Mode { get; init; } = string.Empty;

    /// <summary>Source system connection. Required for Export and Both.</summary>
    public MigrationJobEndpoint? Source { get; init; }

    /// <summary>Target system connection. Required for Import and Both.</summary>
    public MigrationJobEndpoint? Target { get; init; }

    /// <summary>Modules to run and their scope configs.</summary>
    public System.Collections.Generic.List<MigrationJobModule> Modules { get; init; } = new();

    /// <summary>Retry and throttle policies.</summary>
    public MigrationJobPolicies? Policies { get; init; }

    /// <summary>Package location and zip settings.</summary>
    public MigrationJobArtefacts Artefacts { get; init; } = new();

    /// <summary>Guardrails flags that the Job Engine enforces. Both must be true.</summary>
    public MigrationJobGuardrails Guardrails { get; init; } = new();

    /// <summary>SHA-256 of the normalised config JSON at job construction time.</summary>
    public string ConfigHash { get; init; } = string.Empty;
}
