// ──────────────────────────────────────────────────────────────────────────────
// Reqnroll Step Definitions Template
// Generated by the Test Generation Agent.
// Replace MODULE_NAME, FEATURE_NAME, FEATURENAME, MODULE_CLASS with real values.
// Uses Reqnroll (Reqnroll.MSTest).
// ──────────────────────────────────────────────────────────────────────────────
using Reqnroll;
using Moq;
using System.Threading;
using System.Threading.Tasks;
using DevOpsMigrationPlatform.Abstractions;    // adjust namespace as needed

namespace DevOpsMigrationPlatform.MODULE_NAME.Tests.FEATURE_NAME;

// ── Context ───────────────────────────────────────────────────────────────────
// Holds mocks and the system-under-test. Reqnroll injects this via its built-in DI.

public class FEATURENAMEContext
{
    public Mock<IArtefactStore> ArtefactStore { get; } = new(MockBehavior.Strict);
    public Mock<IStateStore> StateStore { get; } = new(MockBehavior.Strict);
    // public Mock<IIdentityMappingService> IdentityMapping { get; } = new(MockBehavior.Strict);

    public MODULE_CLASS Sut { get; }

    // Scenario state — set in Given steps, read in Then steps
    public List<string> ProcessedPaths { get; } = new();

    public FEATURENAMEContext()
        => Sut = new MODULE_CLASS(
            ArtefactStore.Object,
            StateStore.Object
        // , IdentityMapping.Object
        );
}

// ── Step Definitions ──────────────────────────────────────────────────────────

[Binding]
public class FEATURENAMESteps
{
    private readonly FEATURENAMEContext _ctx;

    public FEATURENAMESteps(FEATURENAMEContext ctx) => _ctx = ctx;

    // ── Scenario: SCENARIO_TITLE_1 ────────────────────────────────────────────

    [Given(@"GIVEN_STEP_TEXT_1")]
    public void Given_STEP_NAME_1()
    {
        // TODO: configure _ctx.ArtefactStore / _ctx.StateStore mocks
        throw new PendingStepException();   // Red stage — intentionally failing
    }

    [When(@"WHEN_STEP_TEXT_1")]
    public async Task When_STEP_NAME_1()
    {
        // TODO: await _ctx.Sut.ExportAsync(...) or ImportAsync(...)
        throw new PendingStepException();
    }

    [Then(@"THEN_STEP_TEXT_1")]
    public void Then_STEP_NAME_1()
    {
        // TODO: verify _ctx.ArtefactStore or _ctx.StateStore mock calls
        throw new PendingStepException();
    }

    // ── Scenario: Cursor resume ───────────────────────────────────────────────

    [Given(@"the cursor file at \""(.*?)\"" records the last processed folder as \""(.*?)\""")]
    public void GivenTheCursorRecordsLastProcessed(string cursorFile, string lastPath)
    {
        _ctx.StateStore
            .Setup(s => s.ReadAsync(
                It.Is<string>(k => k == cursorFile),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(lastPath);
        throw new PendingStepException();
    }

    [Then(@"all folders lexicographically less than or equal to \""(.*?)\"" are skipped")]
    public void ThenFoldersBeforeCursorAreSkipped(string cursorPath)
    {
        // TODO: assert _ctx.ProcessedPaths contains no paths <= cursorPath
        throw new PendingStepException();
    }
}
