#if NET7_0_OR_GREATER
using System.Text.Json.Serialization;
#endif

namespace DevOpsMigrationPlatform.Abstractions;

/// <summary>
/// Base class for all job types submitted to the Control Plane.
/// Carries the properties common to every job kind.
///
/// <c>[JsonPolymorphic]</c> enables System.Text.Json to round-trip the concrete
/// subtype through <c>POST /jobs</c> using the <c>"$type"</c> discriminator:
/// <list type="bullet">
///   <item><c>"migration"</c> → <see cref="MigrationJob"/></item>
///   <item><c>"discovery"</c> → <see cref="DiscoveryJob"/></item>
/// </list>
/// </summary>
#if NET7_0_OR_GREATER
[JsonPolymorphic(TypeDiscriminatorPropertyName = "$type")]
[JsonDerivedType(typeof(MigrationJob), "migration")]
[JsonDerivedType(typeof(DiscoveryJob), "discovery")]
#endif
public abstract class Job
{
    /// <summary>Globally unique identifier (UUID v4). Generated by the CLI after pre-validation.</summary>
    public string JobId { get; init; } = string.Empty;

    /// <summary>Config schema version from the source config file.</summary>
    public string ConfigVersion { get; init; } = "1.0";

    /// <summary>SHA-256 of the normalised config JSON at job construction time.</summary>
    public string ConfigHash { get; init; } = string.Empty;

    /// <summary>Retry, throttle, and checkpoint policies.</summary>
    public JobPolicies Policies { get; init; } = new();

    /// <summary>Modules to run and their scope configs.</summary>
    public System.Collections.Generic.List<JobModule> Modules { get; init; } = new();

    /// <summary>Output location. Always a URI — file:/// for standalone, Azure Blob HTTPS URL for hosted.</summary>
    public JobPackage Package { get; init; } = new();

    /// <summary>Guardrails flags that the Job Engine enforces. Both must be true.</summary>
    public JobGuardrails Guardrails { get; init; } = new();

    /// <summary>Optional diagnostics configuration for the agent's log sinks.</summary>
    public JobDiagnostics? Diagnostics { get; init; }

    /// <summary>
    /// Resume options. Null is treated as <see cref="ResumeMode.Auto"/>.
    /// Set to <see cref="ResumeMode.ForceFresh"/> to delete all cursor files and restart from scratch.
    /// </summary>
    public JobResume? Resume { get; init; }
}
