// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) Naked Agility Limited

using DevOpsMigrationPlatform.Abstractions.ControlPlaneApi;

namespace DevOpsMigrationPlatform.Abstractions.Jobs;

/// <summary>
/// Dispatch token handed from the CLI → Control Plane → Agent.
/// Carries only what the ControlPlane needs to route the job to the correct agent.
/// All migration configuration (source, target, modules, policies, organisations) 
/// travels in <c>migration-config.json</c> at the package root (feature 025).
/// See .agents/context/job-contract.md
/// </summary>
public class Job
{
    /// <summary>Globally unique identifier (UUID v4). Generated by the CLI after pre-validation.</summary>
    public string JobId { get; init; } = string.Empty;

    /// <summary>Config schema version. "2.0" = config travels in package (feature 025).</summary>
    public string ConfigVersion { get; init; } = "2.0";

    /// <summary>
    /// What operation the agent should perform.
    /// Used by the agent to dispatch to the correct handler after acquiring the lease.
    /// </summary>
    public JobKind Kind { get; init; }

    /// <summary>
    /// The external systems this job connects to.
    /// Set by the CLI from config. The ControlPlane matches these literally against
    /// agent-advertised connectors — no inference, no mapping.
    /// e.g. [TeamFoundationServer] when source or target is TFS.
    ///      [AzureDevOps] for ADO jobs.
    ///      [] for Simulated (any agent matches).
    /// </summary>
    public ConnectorType[] Connectors { get; init; } = [];

    /// <summary>Optional diagnostics configuration for the agent's log sinks.</summary>
    public JobDiagnostics? Diagnostics { get; init; }

    /// <summary>
    /// Resume options. Null is treated as <see cref="ResumeMode.Auto"/>.
    /// Set to <see cref="ResumeMode.ForceFresh"/> to delete all cursor files and restart from scratch.
    /// </summary>
    public JobResume? Resume { get; init; }

    /// <summary>
    /// Raw JSON contents of the migration-config file.
    /// Set by the CLI from the scenario config file before job submission.
    /// The agent writes this to <c>migration-config.json</c> at the package root on job startup,
    /// before any module reads the config. Null when not provided.
    /// </summary>
    public string? ConfigPayload { get; init; }
}
